language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
secure: "qItYo2LGgq5cKJhaxAo6WqjY2uu/9lIKvKa4JXhCC+hYWMw3RLZH1gu12eRokObHZ4iD+7f2ZObpxzz8uQOvePiFWvXKbMRlCERvaxYwqdPDRvnhkJapJ9yZpsVc2OBs8w+LuHo/9dJi4LPB7YnLJl+30wTEYC44tjIKbHvgq/w="
install:
  - cpanm "Eval::TypeTiny" "Sub::Identify" "Sub::Name" "Test::Fatal" "Test::More" "Types::Standard" "Types::TypeTiny"
script: HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
matrix:
  include:
    - perl: "5.20"
      env: BENCHMARKING=1
      after_success:
        - export GH_NAME=tobyink
        - export GH_EMAIL=tobyink+autobot@cpan.org
        - perl -Ilib devel.scripts/benchmark-to-github.pl
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change
