language: perl
script: HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
install:
  - cpanm "Eval::TypeTiny" "Scope::Upper" "Sub::Identify" "Sub::Name" "Test::Fatal" "Test::More" "Types::Standard" "Types::TypeTiny"
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"
